#!/usr/bin/env node

/**
 * Environment Setup Script for AgriAdvisor Frontend
 * This script helps you configure the backend API URL
 */

const fs = require('fs');
const path = require('path');

console.log('🚀 AgriAdvisor Frontend Environment Setup\n');

// Check if .env.local already exists
const envLocalPath = path.join(__dirname, '.env.local');
if (fs.existsSync(envLocalPath)) {
  console.log('⚠️  .env.local already exists!');
  console.log('Current content:');
  console.log('─'.repeat(50));
  console.log(fs.readFileSync(envLocalPath, 'utf8'));
  console.log('─'.repeat(50));
  
  const readline = require('readline');
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
  
  rl.question('\nDo you want to overwrite it? (y/N): ', (answer) => {
    if (answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes') {
      createEnvFile();
    } else {
      console.log('✅ Keeping existing .env.local file');
      console.log('💡 Edit it manually if you need to change the backend URL');
    }
    rl.close();
  });
} else {
  createEnvFile();
}

function createEnvFile() {
  const readline = require('readline');
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
  
  console.log('🌐 Backend API Configuration\n');
  console.log('Enter your backend server URL:');
  console.log('Examples:');
  console.log('  - http://localhost:8000 (local development)');
  console.log('  - http://192.168.1.100:8000 (local network)');
  console.log('  - https://api.yourapp.com (production)');
  console.log('  - https://staging-api.yourapp.com (staging)\n');
  
  rl.question('Backend API URL: ', (apiUrl) => {
    if (!apiUrl.trim()) {
      apiUrl = 'http://localhost:8000';
      console.log(`⚠️  No URL provided, using default: ${apiUrl}`);
    }
    
    // Validate URL format
    try {
      new URL(apiUrl);
    } catch (error) {
      console.log('❌ Invalid URL format. Please include http:// or https://');
      rl.close();
      return;
    }
    
    // Create .env.local content
    const envContent = `# Backend API Configuration
# Generated by setup-env.js

# Backend API Base URL
NEXT_PUBLIC_API_URL=${apiUrl}

# Environment
NEXT_PUBLIC_ENVIRONMENT=development

# Other configuration
# NEXT_PUBLIC_APP_NAME=AgriAdvisor
# NEXT_PUBLIC_APP_VERSION=1.0.0
`;
    
    try {
      fs.writeFileSync(envLocalPath, envContent, 'utf8');
      console.log('\n✅ .env.local created successfully!');
      console.log('\n📝 File content:');
      console.log('─'.repeat(50));
      console.log(envContent);
      console.log('─'.repeat(50));
      
      console.log('\n🚀 Next steps:');
      console.log('1. Restart your development server: npm run dev');
      console.log('2. Test that API calls work correctly');
      console.log('3. Check browser console for any errors');
      
      console.log('\n💡 To change the backend URL later:');
      console.log('   - Edit .env.local file');
      console.log('   - Restart development server');
      
    } catch (error) {
      console.error('❌ Failed to create .env.local:', error.message);
    }
    
    rl.close();
  });
}
